name: "Car Charger"
version: "0.0.3"
slug: "carchargerslots"
description: "Uses Octopus and BMW Data to find the best times to charge the car."
arch:
  - aarch64
homeassistant_api: true
startup: application
boot: auto
map:
  - addon_config:rw